### ISSUE TITLE
Loading screen for clock

### ISSUE THREAD

**Issue by daniel-moon32** [climateclock/h4i-uiuc-climate-clock-widget#21]
## Learning objectives

- Objective

## Todo

These points are a rough guideline. **Please** feel free to discuss with others on the team about the best way to design this component!

- Todo

## Useful links

- Useful link

## Starter Product Questions

These are some general questions that you can ask Nikhil or Archna. Feel free to ask additional, more in-depth questions, like specifications that you think we overlooked.

- What role does this play within the project?
- Why is it necessary? Is this a nice-to-have?
- Where would users use this feature? In what situation?

**Comment by shwaydogg** [comment]
not a priority
