### ISSUE TITLE
Delete Rate from Lifeline Settings

### ISSUE THREAD

**Issue by Archna-1** [climateclock/h4i-uiuc-climate-clock-widget#77]
## Description
Delete the rate field from the lifeline create / edit modal

**Comment by Paganiniana** [comment]
Is this issue still waiting to get addressed? If so, could you include more context for the decision to remove the rate field? I'm sure it must be simple, so I'll apologize for coming late to the party, here. 😅

**Comment by Archna-1** [comment]
No worries! Looks like I missed this comment. Currently, the rate is increasing per some unit of time (I believe we defined it to update at a set interval); however, sometimes a statistic that is in x / minute or x / second that aligns with our set rate is hard to find. So, for accuracy's sake, we left it off. It was something extra that we thought might be cool, but it was a little out of our timeline to support. Definitely can be added back though, especially if it seems like users are willing to do the calculations to find these rates or if on the code side more time intervals for updates are supported, i.e. minutes, hours, etc.

**Comment by Archna-1** [comment]
@Paganiniana No worries! Looks like I missed this comment. Currently, the rate is increasing per some unit of time (I believe we defined it to update at a set interval); however, sometimes a statistic that is in x / minute or x / second that aligns with our set rate is hard to find. So, for accuracy's sake, we left it off. It was something extra that we thought might be cool, but it was a little out of our timeline to support. Definitely can be added back though, especially if it seems like users are willing to do the calculations to find these rates or if on the code side more time intervals for updates are supported, i.e. minutes, hours, etc.

**Comment by Paganiniana** [comment]
@Archna-1, thanks for your comment. Looks like we're both guilty of some seriously delayed responses. 😅 This "rate" value was causing some problems with the default timeline calculations in another issue (specifically, the "loss and damage" lifeline). I'll just hide this particular form input for now, with the hopes of brining it back, later.

**Comment by shwaydogg** [comment]
will create new issue to address this.
